# .github/workflows/publish-release.yml
name: Publish release
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
          - uses: actions/checkout@v4
          - name: Setup Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.21.x'
          - name: Install dependencies
            run: |
              go get .
              go get github.com/az58740/gRPC_BiDirectional_Microservice.git
              go get github.com/az58740/gRPC_BiDirectional_Microservice.git/max/proto@v1.0.1
              